// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnmvxrsnnnermutkeppe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxubXZ4cnNubm5lcm11dGtlcHBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MzE0OTksImV4cCI6MjA1NjUwNzQ5OX0.nBx-T8dhsiGfGFsT3ZwyFrTHFyGc_079K0Es3EctVIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);